first commit
Mona904/capstone-project pull request #4
Opened 2023-05-09 13:09 UTC by Mona904

2023-05-09 14:23 UTC, Roland-Hufnagel requested changes
Hey Mona. This is a very good first pull-request. Good work. Please have a look at my comments and try to apply it. 
The next time you may want to give your pull-request a more specific name, e.g. 'List overview of plants'.

2023-05-09 14:23 UTC, Roland-Hufnagel commented on components/PlantPage.js
> +
Since this file only renders the `PlantList`-component, there is no need for it. You can render the `PlantList`-component directly from the index.js.

2023-05-09 14:23 UTC, Roland-Hufnagel commented on components/2.jpg
It is not needed. Please delete this file.

2023-05-10 10:09 UTC, Mona904 commented on components/PlantCard.js
> +const Image = styled.img`
I have used the Image- component from next.js.
I have also adjusted the next.config.js but I am getting a server error. Not sure how to proceed.

2023-05-10 14:36 UTC, mbosselmann commented
Hi Mona,
LGTM! 🦊 You can think about Roland`s second remark to change this as it is really not necessary to have an extra `PlantPage` component. But that doesn't stop me from approving your first PR! 🥳

2023-05-10 14:56 UTC, merged